# Generated by Django 5.1.1 on 2024-09-19 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default=0)),
                ('item_id', models.CharField(max_length=15)),
                ('client_id', models.IntegerField(null=True)),
                ('client', models.CharField(max_length=70)),
                ('email', models.CharField(blank=True, max_length=70, null=True)),
                ('product', models.CharField(choices=[('981', 'Norte Verizon'), ('980', 'Norte T-Mobile'), ('979', 'EUA Flex'), ('976', 'EUA Controle'), ('977', 'EUA Ilimitado'), ('975', 'Mundo'), ('974', 'Europa Flex'), ('971', 'Europa Controle')], max_length=50)),
                ('data_day', models.CharField(choices=[('500mb-dia', '500MB/Dia'), ('1gb-dia', '1GB / Dia'), ('2gb-dia', '2GB / Dia'), ('5gb-mes', '5GB / Mês'), ('10gb-mes', '10GB / Mês'), ('20gb-mes', '20GB / Mês'), ('30gb-mes', '30GB / Mês'), ('ilimitado', 'Ilimitado')], max_length=30)),
                ('qty', models.IntegerField()),
                ('coupon', models.CharField(default='', max_length=25)),
                ('days', models.IntegerField()),
                ('countries', models.BooleanField(default=False)),
                ('cell_mod', models.CharField(blank=True, max_length=45, null=True)),
                ('cell_imei', models.CharField(blank=True, max_length=35, null=True)),
                ('cell_eid', models.CharField(blank=True, max_length=35, null=True)),
                ('ord_chip_nun', models.CharField(blank=True, max_length=35, null=True)),
                ('shipping', models.CharField(choices=[('FN', 'Frete Normal'), ('FE', 'Frete Expresso'), ('RT', 'Retirada'), ('MD', 'Mordomo')], default='FN', max_length=20)),
                ('ship', models.CharField(choices=[('FN', 'Frete Normal'), ('FE', 'Frete Expresso'), ('RT', 'Retirada'), ('MD', 'Mordomo')], default='FN', max_length=20)),
                ('order_date', models.DateTimeField()),
                ('activation_date', models.DateField()),
                ('order_status', models.CharField(choices=[('AA', 'Agd. Ativação'), ('AE', 'Agd. Envio'), ('AG', 'Agência'), ('AS', 'Atribuir SIM'), ('AI', 'Atribuir IMEI'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('CN', 'Concluido'), ('DE', 'Desativado'), ('DA', 'Data em Aberto'), ('EA', 'Erro Ativação'), ('ED', 'Erro Desativação'), ('EE', 'Enviar E-mail'), ('ES', 'Em Separação'), ('MB', 'Motoboy'), ('PR', 'Processando'), ('RE', 'Reembolsar'), ('RB', 'Reembolsado'), ('RS', 'Reuso'), ('RP', 'Reprocessar'), ('RT', 'Retirada'), ('VS', 'Verificar SIM')], default='PR', max_length=20)),
                ('type_sim', models.CharField(blank=True, default='sim', max_length=4, null=True)),
                ('oper_sim', models.CharField(blank=True, max_length=2, null=True)),
                ('tracking', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_sim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sims.sims')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'orders',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('type_note', models.CharField(choices=[('S', 'Sistema'), ('P', 'Privada')], default='S', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_notes', to=settings.AUTH_USER_MODEL)),
                ('id_item', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_notes', to='orders.orders')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'notes',
                'ordering': ['-id'],
            },
        ),
    ]
