# Generated by Django 5.0.7 on 2024-08-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ship',
            field=models.CharField(choices=[('FN', 'Frete Normal'), ('FE', 'Frete Expresso'), ('RT', 'Retirada'), ('MD', 'Mordomo')], default='FN', max_length=15),
        ),
    ]
