# Generated by Django 5.0.7 on 2024-10-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ship',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('AA', 'Agd. Ativação'), ('AE', 'Agd. Envio'), ('AG', 'Agência'), ('AS', 'Atribuir SIM'), ('AI', 'Atribuir IMEI'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('CN', 'Concluido'), ('DE', 'Desativado'), ('DA', 'Data em Aberto'), ('EA', 'Erro Ativação'), ('ED', 'Erro Desativação'), ('EE', 'Enviar E-mail'), ('ES', 'Em Separação'), ('EV', 'Entrega VIP'), ('EV', 'Entrega VIP'), ('PC', 'Pag. Confirmado!'), ('PR', 'Processando'), ('RE', 'Reembolsar'), ('RB', 'Reembolsado'), ('RS', 'Reuso'), ('RP', 'Reprocessar'), ('RT', 'Retirada'), ('VS', 'Verificar SIM')], default='PR', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping',
            field=models.CharField(choices=[('AG', 'Aerop. GRU'), ('FG', 'Frete Grátis'), ('FN', 'Frete Normal'), ('EV', 'Entrega VIP'), ('SD', 'SEDEX')], default='FN', max_length=20),
        ),
    ]
