# Generated by Django 5.0.7 on 2024-10-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_order_status_alter_orders_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('3734', 'Amer. Sul Flex'), ('3564', 'Amer. Sul Controle'), ('981', 'Norte Verizon'), ('980', 'Norte T-Mobile'), ('979', 'EUA Flex'), ('976', 'EUA Controle'), ('977', 'EUA Ilimitado'), ('975', 'Mundo'), ('974', 'Europa Flex'), ('971', 'Europa Controle')], max_length=50),
        ),
    ]
