# Generated by Django 5.0.7 on 2024-08-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_ship_alter_orders_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ship',
            field=models.CharField(choices=[('FN', 'Frete Normal'), ('FE', 'Frete Expresso'), ('RT', 'Retirada'), ('MD', 'Mordomo')], max_length=20),
        ),
    ]
