# Generated by Django 5.0.7 on 2024-10-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('AA', 'Agd. Ativação'), ('AE', 'Agd. Envio'), ('AG', 'Aeropoto GRU'), ('AS', 'Atribuir SIM'), ('AI', 'Atribuir IMEI'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('CN', 'Concluido'), ('DE', 'Desativado'), ('DA', 'Data em Aberto'), ('EA', 'Erro Ativação'), ('ED', 'Erro Desativação'), ('EE', 'Enviar E-mail'), ('ES', 'Em Separação'), ('EV', 'Entrega VIP'), ('PC', 'Pag. Confirmado!'), ('PR', 'Processando'), ('RE', 'Reembolsar'), ('RB', 'Reembolsado'), ('RS', 'Reuso'), ('RP', 'Reprocessar'), ('RS', 'Retirada SP'), ('VS', 'Verificar SIM')], default='PR', max_length=4),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('3734', 'Am. Sul Flex'), ('3564', 'Am. do Sul Controle'), ('981', 'Norte Verizon'), ('980', 'Norte T-Mobile'), ('979', 'EUA Flex'), ('976', 'EUA Controle'), ('977', 'EUA Ilimitado'), ('975', 'Mundo'), ('974', 'Europa Flex'), ('971', 'Europa Controle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping',
            field=models.CharField(choices=[('AG', 'Aerop. GRU'), ('FG', 'Frete Grátis'), ('EM', 'E-mail'), ('EV', 'Entrega VIP'), ('FN', 'Frete Normal'), ('SD', 'SEDEX'), ('RS', 'Retirada SP')], default='FN', max_length=20),
        ),
    ]
