# Generated by Django 5.0.7 on 2024-08-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ship',
            field=models.CharField(choices=[('FN', 'Frete Normal'), ('FE', 'Frete Expresso'), ('RT', 'Retirada'), ('MD', 'Mordomo')], default='FN', max_length=20),
        ),
    ]
