# Generated by Django 5.0.7 on 2024-09-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orders_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('981', 'Norte Verizon'), ('980', 'Norte T-Mobile'), ('979', 'EUA Flex'), ('976', 'EUA Controle'), ('977', 'EUA Ilimitado'), ('975', 'Mundo'), ('974', 'Europa Flex'), ('971', 'Europa Controle')], max_length=35),
        ),
    ]
