# Generated by Django 5.0.7 on 2024-10-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orders_order_status_alter_orders_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='data_day',
            field=models.CharField(choices=[('500mb-dia', '500MB/Dia'), ('1gb-dia', '1GB / Dia'), ('2gb-dia', '2GB / Dia'), ('5gb-30dias', '5GB / 30 Dias'), ('10gb-30dias', '10GB / 30 Dias'), ('20gb-30dias', '20GB / 30 Dias'), ('30gb-30dias', '30GB / 30 Dias'), ('1gb-7dias', '1GB / 7 Dias'), ('2gb-7dias', '2GB / 7 Dias'), ('3gb-15dias', '3GB / 15 Dias'), ('4gb-15dias', '4GB / 15 Dias'), ('ilimitado', 'Ilimitado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping',
            field=models.CharField(choices=[('AG', 'Aerop. GRU'), ('FG', 'Frete Grátis'), ('EM', 'E-mail'), ('EL', 'Engrega Loja'), ('EV', 'Entrega VIP'), ('FN', 'Frete Normal'), ('SD', 'SEDEX'), ('RS', 'Retirada SP')], default='FN', max_length=20),
        ),
    ]
