# Generated by Django 5.0.7 on 2025-02-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_data_day_alter_orders_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping',
            field=models.CharField(choices=[('AG', 'Aerop. GRU'), ('FG', 'Frete Grátis'), ('EM', 'E-mail'), ('EL', 'Engrega Loja'), ('EV', 'Entrega VIP'), ('FN', 'Frete Normal'), ('SD', 'SEDEX'), ('RS', 'Retirada SP')], default='FN', max_length=30),
        ),
    ]
