# Generated by Django 5.0.7 on 2026-03-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orders_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='data_day',
            field=models.CharField(choices=[('500mb-dia', '500MB / Dia'), ('1gb-dia', '1GB / Dia'), ('2gb-dia', '2GB / Dia'), ('ilimitado', 'Ilimitado'), ('1gb-periodo', '1GB / Período'), ('2gb-periodo', '2GB / Período'), ('3gb-periodo', '3GB / Período'), ('5gb-periodo', '5GB / Período'), ('10gb-periodo', '10GB / Período'), ('20gb-periodo', '20GB / Período'), ('30gb-periodo', '30GB / Período')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('4769', 'Oriente Flex'), ('4768', 'Asia Flex'), ('4763', 'Africa Flex'), ('4752', 'Cuba Flex'), ('4740', 'Japão Flex'), ('4735', 'Oceania Flex'), ('4718', 'Caribe Flex'), ('3734', 'A. Sul Flex'), ('3564', 'A. Sul Controle'), ('981', 'A. Norte Flex'), ('980', 'A. Norte Controle'), ('976', 'EUA Flex'), ('977', 'EUA Ilimitado'), ('975', 'Mundo Controle'), ('4816', 'Europa Flex (E)'), ('974', 'Europa Flex (F)'), ('971', 'Europa Controle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping',
            field=models.CharField(choices=[('EM', 'E-mail'), ('FG', 'Frete Grátis'), ('LG', 'Loggi'), ('PC', 'Pac'), ('SD', 'SEDEX'), ('RS', 'Retirada SP')], default='FN', max_length=30),
        ),
    ]
