# Generated by Django 5.0.7 on 2026-03-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orders_data_day_alter_orders_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item_id',
            field=models.CharField(max_length=40),
        ),
    ]
