# Generated by Django 5.0.7 on 2026-04-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orders_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='voice',
            field=models.BooleanField(default=False),
        ),
    ]
