# Generated by Django 5.0.7 on 2026-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipping',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
