# Generated by Django 5.0.7 on 2026-08-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='data_day',
            field=models.CharField(choices=[('500mb-dia', '500MB / Dia'), ('1gb-dia', '1GB / Dia'), ('2gb-dia', '2GB / Dia'), ('3gb-dia', '3GB / Dia'), ('ilimitado', 'Ilimitado'), ('1gb-periodo', '1GB / Período'), ('2gb-periodo', '2GB / Período'), ('3gb-periodo', '3GB / Período'), ('5gb-periodo', '5GB / Período'), ('10gb-periodo', '10GB / Período'), ('20gb-periodo', '20GB / Período'), ('30gb-periodo', '30GB / Período')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orders',
            name='oper_sim',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
