# Generated by Django 5.0.7 on 2026-08-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orders_oper_sim_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('AA', 'Agd. Ativação'), ('AE', 'Agd. Envio'), ('AG', 'Aeropoto GRU'), ('AS', 'Atribuir SIM'), ('AI', 'Atribuir IMEI'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('CN', 'Concluido'), ('DE', 'Desativado'), ('DA', 'Data em Aberto'), ('EA', 'Erro Ativação'), ('ED', 'Erro Desativação'), ('EE', 'Enviar E-mail'), ('ES', 'Em Separação'), ('EV', 'Entrega VIP'), ('PC', 'Pag. Confirmado!'), ('PR', 'Processando'), ('RE', 'Reembolsar'), ('RB', 'Reembolsado'), ('RS', 'Reuso'), ('RP', 'Reprocessar'), ('RS', 'Retirada SP'), ('SE', '(e)SIM Esgotado'), ('VS', 'Verificar SIM')], default='PR', max_length=4),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('4769', 'Oriente Flex'), ('4768', 'Asia Flex'), ('4740', 'Japão Flex'), ('3734', 'A. Sul Flex'), ('3564', 'A. Sul Controle'), ('980', 'A. Norte Controle'), ('977', 'EUA Ilimitado'), ('975', 'Mundo Controle'), ('971', 'Europa Controle'), ('001', 'EUA T-mobile'), ('4816', 'Europa Flex (E)'), ('4763', 'Africa Flex'), ('4752', 'Cuba Flex'), ('4735', 'Oceania Flex'), ('4718', 'Caribe Flex'), ('981', 'A. Norte Flex'), ('976', 'EUA Flex'), ('974', 'Europa Flex')], max_length=50),
        ),
    ]
