# Generated by Django 6.0.7 on 2026-09-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orders_order_status_alter_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('4769', 'Oriente Flex'), ('4768', 'Asia Flex'), ('4740', 'Japão Flex'), ('3734', 'A. Sul Flex'), ('3564', 'A. Sul Controle'), ('980', 'A. Norte Controle'), ('977', 'EUA Ilimitado'), ('975', 'Mundo Controle'), ('974', 'Europa Flex'), ('971', 'Europa Controle'), ('001', 'EUA T-mobile')], max_length=50),
        ),
    ]
