# Generated by Django 6.0.7 on 2026-09-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='data_day',
            field=models.CharField(choices=[('500mb-dia', '500MB / Dia'), ('1gb-dia', '1GB / Dia'), ('2gb-dia', '2GB / Dia'), ('3gb-dia', '3GB / Dia'), ('ilimitado', 'Ilimitado'), ('1gb-periodo', '1GB / Período'), ('2gb-periodo', '2GB / Período'), ('3gb-periodo', '3GB / Período'), ('5gb-periodo', '5GB / Período'), ('7gb-periodo', '7GB / Período'), ('10gb-periodo', '10GB / Período'), ('15gb-periodo', '15GB / Período'), ('20gb-periodo', '20GB / Período'), ('30gb-periodo', '30GB / Período')], max_length=30),
        ),
    ]
