# version: '3.8'

services:
  web:
    container_name: djangoapp
    build: .
    command: /djangoapp/scripts/entrypoint.sh
    ports:
      - "80:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/conf.d:/etc/nginx/certbot/conf.d
      - ./nginx/certbot/www:/var/www/certbot
      - ./certs:/etc/nginx/certs
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/conf.d:/etc/nginx/certbot/conf.d
      - ./nginx/certbot/www:/var/www/certbot
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
      
volumes:
  redis-data:
  certs-data: