version: '3.8'

services:
  web:
    container_name: djangoapp
    image: djangoweb:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: /djangoweb/scripts/entrypoint.sh
    networks:
      - public
      - internal
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - IMAGE_NAME=djangoweb:latest
    depends_on:
      - redis
    volumes:
      - logs:/djangoweb/logs
      - /home/sprdmntrdr/docker/django/.env:/djangoweb/.env:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.http.routers.django-http.rule=Host(`painel.worldchip.com.br`)"
      - "traefik.http.routers.django-http.entrypoints=web"
      - "traefik.http.routers.django-http.middlewares=https-redirect"
      - "traefik.http.routers.django-https.rule=Host(`painel.worldchip.com.br`)"
      - "traefik.http.routers.django-https.entrypoints=websecure"
      - "traefik.http.routers.django-https.tls=true"
      - "traefik.http.routers.django-https.tls.certresolver=leresolver"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
    restart: unless-stopped

  celery:
    container_name: celery
    image: djangoweb:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core worker --loglevel=info --concurrency=8 --max-tasks-per-child=50
    networks:
      - internal
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - web
    volumes:
      - logs:/djangoweb/logs
      - /home/sprdmntrdr/docker/django/.env:/djangoweb/.env:ro
    restart: on-failure

  celery_beat:
    container_name: celery_beat
    image: djangoweb:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    networks:
      - internal
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - web
    volumes:
      - logs:/djangoweb/logs
      - /home/sprdmntrdr/docker/django/.env:/djangoweb/.env:ro
    restart: on-failure
    
  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    networks:
      - internal
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    restart: unless-stopped

networks:
  public:
    name: public
    driver: bridge
  internal:
    driver: bridge

volumes:
  redis-data:
    driver: local
  logs:
    driver: local

  