version: '3.8'

services:
  web:
    container_name: djangoapp
    build: .
    command: /djangoapp/scripts/entrypoint.sh
    ports:
      - "80:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
      
  db:
    container_name: postgres
    image: postgres:15.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postg_wchip
      POSTGRES_USER: postg_wchip
      POSTGRES_PASSWORD: GuYr^1ob0j#3
    ports:
      - "5432:5432"

volumes:
  redis-data:
  postgres-data:
  