# version: '3.8'

version: '3.8'

services:
  web:
    container_name: djangoapp
    build: .
    command: /djangoapp/scripts/entrypoint.sh
    env_file:
      - ./.env
    depends_on:
      - redis
    expose:
      - "8000"

  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'"

volumes:
  redis-data:



# services:
#   web:
#     container_name: djangoapp
#     build: .
#     command: /djangoapp/scripts/entrypoint.sh
#     ports:
#       - "8000:8000"
#     env_file:
#       - ./.env
#     depends_on:
#       - redis
#   redis:
#     container_name: redis
#     image: redis:7.2.4-alpine
#     volumes:
#       - redis-data:/data
#     ports:
#       - "6379:6379"
      
# volumes:
#   redis-data:


