# Generated by Django 5.0.7 on 2024-08-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sims',
            name='type_sim',
            field=models.CharField(choices=[('sim', 'SIM (Físico)'), ('esim', 'eSIM (Virtual)')], default='sim', max_length=20),
        ),
    ]
