# Generated by Django 5.0.7 on 2026-03-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sims',
            name='operator',
            field=models.CharField(choices=[('AR', 'Airalo'), ('CM', 'China Mobile'), ('TM', 'T-Mobile'), ('TC', 'Telcom'), ('VR', 'Verizon')], max_length=20),
        ),
    ]
