# Generated by Django 5.0.7 on 2026-05-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.CharField(choices=[('esim_eua', 'eSIM EUA'), ('esim_other', 'eSIM Outros'), ('sim_all', 'SIM Físico')], max_length=20, unique=True, verbose_name='Tipo de template')),
                ('content', models.TextField(verbose_name='Conteúdo (HTML)')),
            ],
            options={
                'verbose_name': 'Template de e-mail',
                'verbose_name_plural': 'Templates de e-mail',
            },
        ),
    ]
