# Generated by Django 5.0.7 on 2026-05-27 14:57

from django.db import migrations

ESIM_EUA_CONTENT = """<p><strong>INFORMAÇÕES DE USO</strong></p>

<p>Você adquiriu um eSIM da WorldChip. A instalação é rápida e simples — siga o passo a passo abaixo:</p>
<br>

<p><strong>Antes de começar</strong></p>
<ul>
  <li>Conecte-se a uma rede Wi-Fi</li>
  <li>Ative os dados móveis</li>
  <li>EXCLUA TODOS OS eSIMs DE VIAGENS ANTERIORES (OBRIGATÓRIO)</li>
  <li>Realize a instalação somente na data de ativação informada no seu plano</li>
</ul>

<p><strong>Instalação do eSIM</strong></p>
<br>

<p><strong>iPhone</strong></p>
<p>1. Acesse Ajustes</p>
<p>2. Toque em Celular</p>
<p>3. Toque em Adicionar eSIM</p>
<p>4. Selecione Usar código QR</p>
<p>5. Escaneie o QR Code</p>
<p>6. Siga as instruções na tela</p>
<p>7. Defina o eSIM WorldChip como principal para dados</p>
<p>8. Ative o Roaming de Dados</p>
<br>
<p><strong>Android</strong></p>
<p>1. Acesse Configurações</p>
<p>2. Toque em Conexões ou Rede e Internet</p>
<p>3. Acesse Gerenciador de SIM / eSIM</p>
<p>4. Toque em Adicionar eSIM</p>
<p>5. Escaneie o QR Code</p>
<p>6. Siga as instruções na tela</p>
<p>7. Defina o eSIM WorldChip como padrão para dados móveis</p>
<p>8. Ative o Roaming de Dados</p>
<br>

<p><strong>Importante</strong></p>
<ul>
  <li>O eSIM é vinculado ao aparelho no momento da instalação</li>
  <li>O eSIM NÃO pode ser deletado após a instalação, pois não poderá ser utilizado novamente</li>
  <li>Não será possível transferi-lo para outro dispositivo após ativação. Para qualquer necessidade, consulte nosso atendimento</li>
</ul>
<br>"""

ESIM_OTHER_CONTENT = """<p><strong>INFORMAÇÕES DE USO</strong></p>

<p>Você adquiriu um eSIM da WorldChip. A instalação é rápida e simples — siga o passo a passo abaixo:</p>
<br>

<p><strong>Antes de começar</strong></p>
<ul>
  <li>Conecte-se a uma rede Wi-Fi</li>
  <li>Ative os dados móveis</li>
  <li>EXCLUA TODOS OS eSIMs DE VIAGENS ANTERIORES (OBRIGATÓRIO)</li>
  <li>Realize a instalação somente na data de ativação informada no seu plano</li>
</ul>

<p><strong>Instalação do eSIM</strong></p>
<br>

<p><strong>iPhone</strong></p>
<p>1. Acesse Ajustes</p>
<p>2. Toque em Celular</p>
<p>3. Toque em Adicionar eSIM</p>
<p>4. Selecione Usar código QR</p>
<p>5. Escaneie o QR Code</p>
<p>6. Siga as instruções na tela</p>
<p>7. Defina o eSIM WorldChip como principal para dados</p>
<p>8. Ative o Roaming de Dados</p>
<br>
<p><strong>Android</strong></p>
<p>1. Acesse Configurações</p>
<p>2. Toque em Conexões ou Rede e Internet</p>
<p>3. Acesse Gerenciador de SIM / eSIM</p>
<p>4. Toque em Adicionar eSIM</p>
<p>5. Escaneie o QR Code</p>
<p>6. Siga as instruções na tela</p>
<p>7. Defina o eSIM WorldChip como padrão para dados móveis</p>
<p>8. Ative o Roaming de Dados</p>
<br>

<p><strong>Importante</strong></p>
<ul>
  <li>O eSIM é vinculado ao aparelho no momento da instalação</li>
  <li>O eSIM NÃO pode ser deletado após a instalação, pois não poderá ser utilizado novamente</li>
  <li>Não será possível transferi-lo para outro dispositivo após ativação. Para qualquer necessidade, consulte nosso atendimento</li>
</ul>
<br>"""

SIM_ALL_CONTENT = """<p><strong>INFORMAÇÕES DE USO</strong></p>

<p>Você adquiriu um chip físico WorldChip. A instalação é rápida e simples — siga o passo a passo abaixo:</p>
<br>

<p><strong>Antes de começar</strong></p>
<ul>
  <li>Realize a ativação somente na data informada no seu plano</li>
  <li>Certifique-se de que seu aparelho está desbloqueado para uso internacional</li>
</ul>
<br>

<p><strong>Instalação do Chip</strong></p>
<br>

<p><strong>iPhone</strong></p>
<p>1. Desligue o aparelho</p>
<p>2. Remova o chip atual</p>
<p>3. Insira o WorldChip</p>
<p>4. Ligue o aparelho</p>
<p>5. Vá em Ajustes > Celular</p>
<p>6. Selecione o chip WorldChip como padrão para dados</p>
<p>7. Ative o Roaming de Dados</p>

<p><strong>Android</strong></p>
<p>1. Desligue o aparelho</p>
<p>2. Remova o chip atual</p>
<p>3. Insira o WorldChip</p>
<p>4. Ligue o aparelho</p>
<p>5. Vá em Configurações > Conexões / Rede móvel</p>
<p>6. Selecione o chip WorldChip como padrão para dados</p>
<p>7. Ative o Roaming de Dados</p>

<p><strong>Importante</strong></p>
<ul>
  <li>Em aparelhos Dual SIM, utilize o WorldChip na posição 1 e remova o outro chip para evitar incompatibilidades</li>
  <li>Seu WhatsApp continuará funcionando normalmente, pois está vinculado ao aparelho</li>
  <li>Para qualquer dúvida, alteração ou necessidade, consulte nosso atendimento</li>
</ul>
<br>"""


def populate_templates(apps, schema_editor):
    Templates = apps.get_model('send_email', 'Templates')
    Templates.objects.bulk_create([
        Templates(name='eSIM EUA', slug='esim_eua', content=ESIM_EUA_CONTENT),
        Templates(name='eSIM Outros', slug='esim_other', content=ESIM_OTHER_CONTENT),
        Templates(name='SIM Físico', slug='sim_all', content=SIM_ALL_CONTENT),
    ])


def reverse_populate(apps, schema_editor):
    Templates = apps.get_model('send_email', 'Templates')
    Templates.objects.filter(slug__in=['esim_eua', 'esim_other', 'sim_all']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_templates, reverse_populate),
    ]
